### ISSUE TITLE
removeruleset error

### ISSUE THREAD

**Issue by MartynenkoA** [zebzhao/Angular-QueryBuilder#30] opened 2018-03-14 15:23 UTC
in your custom material demo https://zebzhao.github.io/Angular-QueryBuilder/demo/ in the root exists removeruleset button http://prntscr.com/ir52jm, and its not working. i think there is not be there

**Comment by MartynenkoA** [comment] 2018-03-14 15:25
oh, i saw another issue with the same error

**Comment by zebzhao** [comment] 2018-03-18 16:13
Duplicate of #27

**Closed by zebzhao** 2018-03-18 16:13 UTC
